### ISSUE TITLE
Add support for SLERP

### ISSUE THREAD

**Issue by paf31** [hdgarrood/purescript-quaternions#1]
Great library! I think it would be great to add support for spherical linear interpolation ([SLERP](https://en.wikipedia.org/wiki/Slerp)) which is quite natural with a presentation in terms of quaternions.

**Comment by hdgarrood** [comment]
Thanks :) Sounds good, yeah. I am going to try to learn a bit more about 3D graphics first, this is all still quite new to me.

Are you imagining:

``` purescript
slerp :: Rotation Number -> Rotation Number -> Number -> Rotation Number
```

where the third parameter is in [0,1]?

**Comment by paf31** [comment]
Yes, exactly.
