### ISSUE TITLE
Is CommutativeRing (Quaternion a) intentional?

### ISSUE THREAD

**Issue by MaloJaffre** [hdgarrood/purescript-quaternions#3]
Quaternions aren't commutative rings, but there is an [`instance commutativeRingQuaternion :: CommutativeRing a => CommutativeRing (Quaternion a)`](https://github.com/hdgarrood/purescript-quaternions/blob/master/src/Data/Quaternion.purs#L51).

Also, Num is mentioned in Quaternion documentation, but this typeclass doesn't exist in purescript libraries.

**Comment by hdgarrood** [comment]
Wow that was quick! Yes I'm working on a fix now.

**Comment by hdgarrood** [comment]
Ok, I've published v2.0.0. Would you mind having a quick read through to see if you think it looks okay now?

**Comment by MaloJaffre** [comment]
Thanks for fixing this quickly.
Yeah, it looks good now, and the docs are fantastic!

**Comment by hdgarrood** [comment]
Great, thanks very much!
