### ISSUE TITLE
pulp test shirks tests

### ISSUE THREAD

**Issue by Gerstacker** [hdgarrood/purescript-quaternions#4]
This doesn't feel like a purescript-quaternions problem, more likely lower level. But this is where I've made a test case. Please look at the tip of master in https://github.com/Gerstacker/purescript-quaternions.git
For the tip commit bb29be, "pulp test" reliably produces "Tests OK." with no evidence that it's actually run any tests. The only changes are import specifications and type annotations to fix compiler warnings.
Rolling back to the previous commit 4bfcdb, output is as expected. Rolling forward again, same failure.

pulp version 11.0.2
purs version 0.11.6

If I'm missing something dumb, please say so!

**Comment by hdgarrood** [comment]
Don't worry, that's a very easy mistake to make! I've left a comment in the repo.
