### ISSUE TITLE
Should toMat4 actually return a 3x3 matrix?

### ISSUE THREAD

**Issue by hdgarrood** [hdgarrood/purescript-quaternions#6]
cc @Gerstacker 

I've decided to drop the purescript-matrix and purescript-vector dependencies because they do not seem to be being kept up-to-date, and because there doesn't (yet) seem to be a standard linear algebra library for purescript. Now `Data.Quaternion.Rotation.toMat4` just produces an array in row-major order, which means that all you have to do is call `Mat4.mat4` on the result to get back the previous behaviour.

In the process of doing this, however, I realised that `toMat4` is not very well documented, and also I'm not entirely sure what it actually represents. Unit quaternions represent rotations in 3 dimensions, so if we are providing a function which converts a quaternion to a rotation matrix, wouldn't it make sense to have it produce a 3x3 matrix rather than a 4x4 one? Especially since the current implementation is essentially gives you a 3x3 matrix, since it doesn't do anything to the fourth element when applied to an element of R^4. In fact the current implementation seems to be doing the same thing as in this Wikipedia article: https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions#Rotation_matrix_.E2.86.94_quaternion

**Comment by Gerstacker** [comment]
I agree overall, Harry. toMat3 would be fine somewhere else that depends on both purescript-quaternions and some matrix/vector library. It should in some sense be generic over the latter.

toMat4 was a convenience that probably doesn't belong in purescript-quaternions. In graphics it's customary to represent rotations, translations, and various other transformations as 4x4 matrices in [homogeneous coordinates](https://en.wikipedia.org/wiki/Homogeneous_coordinates#Use_in_computer_graphics_and_computer_vision). This lets you conveniently compose a chain of transformations with 4x4 matrix multiplications regardless of the types of transformations and their order. Strictly speaking it's more efficient to compose rotations by multiplying quaternions, compose translations by adding 3-vectors, etc. But once you want to compose a rotation with a translation you might as well put them both in 4x4 homogeneous matrices and proceed with matrix multiplication.

**Comment by hdgarrood** [comment]
Ah, I see - thanks for the explanation! I'm actually thinking now that I might as well put functions for converting to and from 3x3 rotation matrices in here; it's simple enough to do so, they're likely to be useful to someone at some point, and I think it ought to be easy enough to convert to and from the representation used by whatever matrix/vector library if I just use arrays in a similar manner to how `toMat4` currently does?

**Comment by Gerstacker** [comment]
I think that's a great plan.
